removed duplicate docs for scripts & added help options to all scripts

diff --git a/show-help b/show-help
--- a/show-help
+++ b/show-help
@@ -1,7 +1,4 @@
 #!/usr/bin/env bash
-#
-# Noah Huppert - 10/22/17
-#
 #?
 # Prints the help documentation located in the top comments of a script. 
 # More specifically the text between the two "#?" help tags. These help tags 
@@ -20,45 +17,41 @@
 # 	No arguments provided: Exits with error
 #	All arguments provided: Prints the text between the help tags in the 
 #				top comment of the file
-#
-# Return Values:
-# 	0: 	       Success
-# 	Anything Else: Failure
 #?
 
 # Options
 # While more than one arg, process option and shift
-while (( "$#" > 1 )); do
-	# Process option
-	if [[ "$1" =~ ^(--scripts|-s)$ ]]; then
-		scriptsDirOption=true
-	else
-		echo "Error: Unknown option \"$1\""
-		exit 1
-	fi
+while [ ! -z "$1" ]; do
+	case "$1" in
+		--scripts|-s)
+			scriptsDirOption=true
+			;;
+		--help|-h)
+			show-help "$0"
+			exit 1
+			;;
+		*)
+			filePath="$1"
+			;;
+	esac
 
-	# Shift
 	shift
 done
 
-# Check first arg
-# If not provided
-if [[ -z "$1" ]]; then
-	show-help -s show-help
-	echo "Error: Expected 1 argument"
+# Check file path provided
+if [ -z "$filePath" ]; then
+	echo "Error: File argument must be provided" >&2
 	exit 1
 fi
 
 # If file path should be in scripts dir, as described in help text
 if [[ "$scriptsDirOption" ]]; then
-	filePath="$HOME/Documents/bin/scripts/$1"
-else
-	filePath="$1"
+	filePath="$HOME/Documents/bin/scripts/$filePath"
 fi
 
 # If doesn't exist
 if [[ ! -f "$filePath" ]]; then
-	echo "Provided file \"$filePath\" does not exist"
+	echo "Provided file \"$filePath\" does not exist" >&2
 	exit 1
 fi
 
diff --git a/sslinfo b/sslinfo
--- a/sslinfo
+++ b/sslinfo
@@ -27,58 +27,58 @@
 # Behavior:
 # 	All arguments provided: prints ssl certificate information to stdout
 # 	No arguments provided: Print this help text
-#
-# Return Values:
-#	0             = Success
-# 	Anything else = Failure
 #?
 
 # Options
-while (( "$#" > 1 )); do
-	# Process first argument (Since options come first), and shift. Until 
-	# only one argument is left (Hopefully the URL).
-	# trim option
-	if [[ "$1" =~ --?t(rim)? ]]; then
-		trim=true
-	# page option
-	elif [[ "$1" =~ --?p(age)? ]]; then
-		# Check $PAGER environment variable is configured
-		if [[ -z "$PAGER" ]]; then
-			echo "Error: Page option provided but \$PAGER environment variable not set"
+while [ ! -z "$1" ]; do
+	case "$1" in
+		--trim|-t)
+			trim=true
+			;;
+		--page|-p)
+			# Check $PAGER environment variable is configured
+			if [[ -z "$PAGER" ]]; then
+				echo "Error: Page option provided but \$PAGER environment variable not set" >&2
+				exit 1
+			fi
+			page=true
+			;;
+		--help|-h)
+			show-help "$0"
 			exit 1
-		fi
-		page=true
-	else
-		echo "Error: Unknown option \"$1\""
-		exit 1
-	fi
+			;;
+		*)
+			host="$1"
+			;;
+	esac
 
 	shift
 done
 
-# Check if help
-if [[ ( -z "$1" ) || ( "$1" =~ "-*[Hh](?:elp)?$" ) ]]; then
-	show-help -s sslinfo
-# Show ssl info
+# Arguments
+if [ -z "$host" ]; then
+	echo "Error: host argument must be provided" >&2
+	exit 1
+elif ! [[ "$host" =~ ^([a-zA-Z0-9]+\.)+[a-zA-Z0-9]+$ ]]; then
+	echo "Error: Invalid host \"$host\"" >&2
+	exit 1
+fi
+
+# Openssl trick for getting cert info from SO: 
+# https://serverfault.com/a/661982
+info=$(echo | \
+openssl s_client -showcerts -servername "$host" -connect "$host:443" 2>/dev/null | \
+openssl x509 -inform pem -noout -text)
+
+# Trim if requested
+if [[ "$trim" ]]; then
+	info=$(echo "$info" | sed -e '/\([0-9a-fA-F]\{2\}:\)\{2,\}/d')
+fi
+
+# Output info
+# Page if requested
+if [[ "$page" ]]; then
+	echo "$info" | $PAGER
 else
-	host="$1"
-
-	# Openssl trick for getting cert info from SO: 
-	# https://serverfault.com/a/661982
-	info=$(echo | \
-	openssl s_client -showcerts -servername "$host" -connect "$host:443" 2>/dev/null | \
-	openssl x509 -inform pem -noout -text)
-
-	# Trim if requested
-	if [[ "$trim" ]]; then
-		info=$(echo "$info" | sed -e '/\([0-9a-fA-F]\{2\}:\)\{2,\}/d')
-	fi
-
-	# Output info
-	# Page if requested
-	if [[ "$page" ]]; then
-		echo "$info" | $PAGER
-	else
-		echo "$info"
-	fi
+	echo "$info"
 fi
